mel-checkout: fix tty handling for the prompt
Once we're in prompt_choice, we can no longer test stdin or stdout to see if
it's a tty, since stdin is used to feed the prompt choices, so test for it
outside the function and pass an argument to force non-interactive mode when
appropriate.

Signed-off-by: Christopher Larson <chris_larson@mentor.com>

diff --git a/scripts/release/mel-checkout b/scripts/release/mel-checkout
--- a/scripts/release/mel-checkout
+++ b/scripts/release/mel-checkout
@@ -3,6 +3,17 @@
 set -eu
 
 prompt_choice () {
+    non_interactive=0
+    unset OPTIND OPTARG
+    while getopts n opt; do
+        case "$opt" in
+            n)
+                non_interactive=1
+                ;;
+        esac
+    done
+    shift $(expr $OPTIND - 1)
+
     prompt_message="$1"
     prompt_default="${2:-}"
 
@@ -24,9 +35,9 @@ prompt_choice () {
             ;;
     esac
 
-    if [ ! -t 0 ] || [ ! -t 2 ]; then
-        # We only prompt when running on a tty
-        return 2
+    if [ $non_interactive -eq 1 ]; then
+        printf >&2 'Error: unable to prompt for `%s` interactively\n' "$prompt_message"
+        return 1
     fi
 
     if [ -n "$prompt_default" ] && \
@@ -35,7 +46,6 @@ prompt_choice () {
         prompt_default=
     fi
 
-    prompt_value=
     while [ -z "$prompt_value" ]; do
         prompt_num=0
         while read choice; do
@@ -59,10 +69,15 @@ prompt_choice () {
     rm -f "$prompt_options"
 }
 
-prompt_manifest() {
+prompt_manifest () {
+    if ! [ -t 1 ] || ! [ -t 0 ]; then
+        non_interactive=-n
+    else
+        non_interactive=
+    fi
     find "$1" -maxdepth 1 -type f -name \*.manifest | \
         sed 's,^.*/,,' | sort -rn | \
-        ( set +u; prompt_choice "$2" 1; ) | sed "s,^,$1/,"
+        ( set +u; prompt_choice $non_interactive "$2" 1; ) | sed "s,^,$1/,"
 }
 
 
