mel-checkout: improve robustness, avoid re-initing git repos
Signed-off-by: Christopher Larson <chris_larson@mentor.com>

diff --git a/scripts/release/mel-checkout b/scripts/release/mel-checkout
--- a/scripts/release/mel-checkout
+++ b/scripts/release/mel-checkout
@@ -1,8 +1,10 @@
 #!/bin/sh
 
+set -eu
+
 prompt_choice () {
     prompt_message="$1"
-    prompt_default="$2"
+    prompt_default="${2:-}"
 
     prompt_options="$(mktemp prompt-choice.XXXXXX)"
     cat >>"$prompt_options"
@@ -33,6 +35,7 @@ prompt_choice () {
         prompt_default=
     fi
 
+    prompt_value=
     while [ -z "$prompt_value" ]; do
         prompt_num=0
         while read choice; do
@@ -56,62 +59,78 @@ prompt_choice () {
     rm -f "$prompt_options"
 }
 
+if [ $# -eq 0 ] || [ "$1" = "-h" ]; then
+    echo >&2 "Usage: ${0##*/} BUILD_DIR [MANIFEST_FILE]"
+    echo >&2
+    echo >&2 "If no manifest file is specified, a prompt will be shown to"
+    echo >&2 "interactively select one of the manifests in the same mel"
+    echo >&2 "installation as this script."
+    exit 1
+fi
+
 scriptdir="$(cd "$(dirname "$0")" && pwd -P)"
 project="$1"
-manifest="$2"
-
-if [ -z "$manifest" ]; then
-    if [ -e "$project/.manifest" ]; then
-        manifest="$(cat "$project/.manifest")"
-        echo >&2 "Using manifest $manifest for $project"
-    else
-        tmpfile="$(mktemp -t "${0##*/}.XXXXX")"
-        trap 'rm -f "$tmpfile"' EXIT INT TERM
-        find "$scriptdir/manifests" -maxdepth 1 -type f -name \*.manifest | \
-            sed 's,^.*/,,' | sort -rn | prompt_choice "Select manifest" 1 >$tmpfile
-        manifest="$(cat "$tmpfile")"
-        if [ -z "$manifest" ]; then
-            echo >&2 "Error: no manifest found, please specify"
-            exit 1
-        else
-            manifest="$scriptdir/manifests/$manifest"
-        fi
-    fi
-fi
+manifest="${2:-}"
 
 mkdir -p "$project"
 cd "$project"
+
+if [ -z "$manifest" ]; then
+    if ! [ -e "$project/.manifest" ]; then
+        find "$scriptdir/manifests" -maxdepth 1 -type f -name \*.manifest | \
+            sed 's,^.*/,,' | sort -rn | ( set +u; prompt_choice "Select manifest" 1; ) | sed "s,^,$scriptdir/manifests/," >"$project/.manifest"
+        if ! [ -s "$project/.manifest" ]; then
+            echo >&2 "Error: no manifest found, please specify"
+            rm -f "$project/.manifest"
+            exit 1
+        fi
+    fi
+    manifest="$(cat "$project/.manifest")"
+    echo >&2 "Using manifest $manifest for $project"
+else
+    echo "$manifest" >"$project/.manifest"
+fi
+
 {
     cat "$manifest"
     cat "$scriptdir/manifests/extra/"*.manifest 2>/dev/null || :
 } | sort -u | while read -r checkout_path commit remote; do
-    git init "$checkout_path"
+    if [ ! -d "$checkout_path/.git" ]; then
+        git init "$checkout_path"
+    fi
+
     cd "$checkout_path"
     echo "$scriptdir/objects" >.git/objects/info/alternates
     echo "$commit" >.git/shallow
     if [ -n "$remote" ]; then
-        git remote add origin "$remote"
+        if git remote | grep -qxF origin; then
+            git remote set-url origin "$remote"
+        else
+            git remote add origin "$remote"
+        fi
     fi
 
     # Create branches for all manifests, for reference
-    for otherfn in "$manifest" "$scriptdir/manifests/"*.manifest; do
+    for otherfn in "$scriptdir/manifests/"*.manifest; do
         while read -r other_checkout_path other_commit _; do
             if [ "$other_checkout_path" = "$checkout_path" ]; then
-                git branch "$(basename "${otherfn%.manifest}")" "$other_commit"
+                branch="$(basename "${otherfn%.manifest}")" 
+                if ! git rev-parse -q --verify "refs/heads/$branch" >/dev/null; then
+                    git update-ref "refs/heads/$branch" "$other_commit"
+                fi
                 echo "$other_commit" >>.git/shallow
             fi
         done <"$otherfn"
     done
-    git checkout "$(basename "${manifest%.manifest}")"
+    branch="$(basename "${manifest%.manifest}")"
+    if ! git rev-parse -q --verify "refs/heads/$branch" >/dev/null; then
+        git update-ref "refs/heads/$branch" "$commit"
+    fi
+    if [ "$(git rev-parse -q --verify --symbolic-full-name HEAD 2>/dev/null)" != "refs/heads/$branch" ]; then
+        git checkout "$branch"
+    fi
 
     cd - >/dev/null
-done
-echo "$manifest" >.manifest
-
-for dir in downloads cached-binaries; do
-    if [ -e "$scriptdir/$dir" ]; then
-        ln -sf "$scriptdir/$dir" .
-    fi
 done
 
 if [ -e "${manifest%.manifest}.info" ]; then
@@ -121,3 +140,9 @@ if [ -e "${manifest%.manifest}.info" ]; then
         ln -s "$scriptdir/$bspfiles_path" "${bspfiles_path%/*}"
     fi
 fi
+
+for dir in downloads cached-binaries; do
+    if [ -e "$scriptdir/$dir" ]; then
+        ln -sf "$scriptdir/$dir" . || :
+    fi
+done
