release/setup-environment: add -m MANIFEST arg
The user can now specify the manifest rather than being prompted for it.

Signed-off-by: Christopher Larson <chris_larson@mentor.com>

diff --git a/scripts/release/setup-environment b/scripts/release/setup-environment
--- a/scripts/release/setup-environment
+++ b/scripts/release/setup-environment
@@ -10,6 +10,33 @@ else
     fi
     scriptdir=`readlink -f "$scriptdir"`
 
+    mel_quote(){
+        sed -e "s,','\\\\'',g; 1s,^,',; \$s,\$,',;" << EOF
+    $1
+EOF
+    }
+
+    mel_save () {
+        case "$1" in
+        # when a string contains a "'" we have to escape it
+        *\'*)
+            mel_saved="$mel_saved $(mel_quote "$1")"
+            ;;
+        # otherwise just quote the variable
+        *)
+            mel_saved="$mel_saved '$1'"
+            ;;
+        esac
+    }
+
+    mel_abspath () {
+        _path="$1"
+        if [ -n "${_path##/*}" ]; then
+            _path="$PWD/$1"
+        fi
+        echo "$_path"
+    }
+
     if [ -f conf/local.conf -o -f conf/bblayers.conf ]; then
         # Assuming we're already in the build dir
         BUILDDIR=$PWD
@@ -17,8 +44,11 @@ else
         BUILDDIR=$PWD/build
     fi
 
+    mel_saved=
+    mel_manifest=
     mel_fail=0
-    for mel_argnum in $(seq $#); do
+    mel_argnum=1
+    while [ $mel_argnum -le $# ]; do
         mel_arg="$(eval printf "%s" "\$$mel_argnum")"
         case "$mel_arg" in
             -b)
@@ -26,18 +56,41 @@ else
                 if [ -z "$BUILDDIR" ]; then
                     echo >&2 "-b requires an argument"
                     mel_fail=1
+                else
+                    BUILDDIR="$(mel_abspath "$BUILDDIR")"
                 fi
                 ;;
+            -m)
+                mel_manifest="$(eval printf "%s" "\$$(expr $mel_argnum + 1)")"
+                mel_argnum="$(expr $mel_argnum + 1)"
+                if [ -z "$mel_manifest" ]; then
+                    echo >&2 "-m requires an argument"
+                    mel_fail=1
+                else
+                    mel_argnum="$(expr $mel_argnum + 1)"
+                    if [ ! -e "$mel_manifest" ]; then
+                        echo >&2 "Error: manifest path $mel_manifest does not exist"
+                        mel_fail=1
+                    else
+                        mel_manifest="$(mel_abspath "$mel_manifest")"
+                    fi
+                fi
+                continue
+                ;;
         esac
+        mel_save "$mel_arg"
+        mel_argnum="$(expr $mel_argnum + 1)"
     done
-    unset mel_argnum mel_arg
+    eval set -- "$mel_saved"
+    unset mel_saved mel_argnum mel_arg
+    unset mel_save mel_quote mel_abspath
 
     if [ $mel_fail -eq 0 ]; then
-        "$scriptdir/mel-checkout" "$BUILDDIR" && \
+        "$scriptdir/mel-checkout" "$BUILDDIR" "$mel_manifest" && \
             cd "$BUILDDIR" && . ./meta-mentor/setup-environment "$@" -b .
         mel_fail=$?
     fi
-    unset scriptdir
+    unset mel_manifest scriptdir
     test $mel_fail -eq 0
 fi
 # vim: set ft=sh :
